//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public int ID { get; set; }
        public int Cats { get; set; }
        public string Cat_Breeds { get; set; }
        public int Dogs { get; set; }
        public string Dog_Breeds { get; set; }
        public int Fish { get; set; }
        public string Fish_Breeds { get; set; }
        public Nullable<int> Rodents { get; set; }
        public string Rodent_Breeds { get; set; }
    }
}
